# Visualization settings for interactive mode

/run/initialize

/vis/open OGL 600x600-0+0

/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointThetaPhi 90 0
/vis/viewer/set/lightsVector 0 0 -1
/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/lineSegmentsPerCircle 100

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

/vis/scene/endOfEventAction accumulate

/vis/geometry/set/visibility World 0 false

/vis/scene/add/axes 0 0 0 1 m

/vis/viewer/set/autoRefresh true
/vis/verbose warnings
